import React, { useEffect, useState } from 'react';
import { SafeAreaView, StyleSheet } from 'react-native';
import {
  getGeoLocation,
  getStudentForm,
  reverseGeocode,
} from '../../utils/API/AuthService';
import Loading from '../LoadingScreen/Loading';
import {
  getDataFromStorage,
  setDataInStorage,
} from '../../utils/JsHelper/Helper';
import NetworkAlert from '../../components/NetworkError/NetworkAlert';
import RegistrationForm from './RegistrationForm';
import Geolocation from 'react-native-geolocation-service'; // GeoLocation Comment

const RegisterScreen = () => {
  const [mainSchema, setMainSchema] = useState([]);
  const [loading, setLoading] = useState(true);
  const [networkError, setNetworkError] = useState(false);
  const [geoData, setgeoData] = useState();

  const fetchstates = async () => {
    const payload = {
      limit: 10,
      offset: 0,
      fieldName: 'state',
    };
    const data = await getGeoLocation({ payload });
    setDataInStorage('states', JSON.stringify(data?.values || []));
    return data?.values;
  };

  // GetLocation Comment

  const getLocationFromGoogle = async () => {
    Geolocation.getCurrentPosition(
      async (position) => {
        const data = await reverseGeocode(
          position?.coords?.latitude,
          position?.coords?.longitude
        );
        await setDataInStorage('geoData', JSON.stringify(data));
      },
      (error) => {
        console.log('Error: ', error);
      },
      { enableHighAccuracy: true, timeout: 15000, maximumAge: 10000 }
    );
  };

  const getLocation = async () => {
    await getLocationFromGoogle();
    const data = JSON.parse(await getDataFromStorage('geoData'));
    setgeoData(data);
  };

  // const fields = [
  //   {
  //     hint: null,
  //     name: 'firstName',
  //     type: 'text',
  //     label: 'first_name',
  //     order: '1',
  //     fieldId: null,
  //     options: [],
  //     pattern: '/^[A-Za-z]+$/',
  //     coreField: 1,
  //     dependsOn: null,
  //     maxLength: null,
  //     minLength: 3,
  //     isEditable: true,
  //     isPIIField: null,
  //     isRequired: true,
  //     validation: ['string'],
  //     placeholder: 'ENTER_FIRST_NAME',
  //     isMultiSelect: false,
  //     maxSelections: 0,
  //     sourceDetails: {},
  //   },
  //   {
  //     hint: null,
  //     name: 'middleName',
  //     type: 'text',
  //     label: 'middle_name',
  //     order: '1',
  //     fieldId: null,
  //     options: [],
  //     pattern: '/^[A-Za-z]+$/',
  //     coreField: 1,
  //     dependsOn: null,
  //     maxLength: null,
  //     minLength: 3,
  //     isEditable: true,
  //     isPIIField: null,
  //     isRequired: false,
  //     validation: ['string'],
  //     placeholder: 'ENTER_MIDDLE_NAME_OR_FATHER_NAME',
  //     isMultiSelect: false,
  //     maxSelections: 0,
  //     sourceDetails: {},
  //   },
  //   {
  //     hint: null,
  //     name: 'lastName',
  //     type: 'text',
  //     label: 'last_name',
  //     order: '1',
  //     fieldId: null,
  //     options: [],
  //     pattern: '/^[A-Za-z]+$/',
  //     coreField: 1,
  //     dependsOn: null,
  //     maxLength: null,
  //     minLength: 3,
  //     isEditable: true,
  //     isPIIField: null,
  //     isRequired: true,
  //     validation: ['string'],
  //     placeholder: 'ENTER_LAST_NAME',
  //     isMultiSelect: false,
  //     maxSelections: 0,
  //     sourceDetails: {},
  //   },
  //   {
  //     hint: null,
  //     name: 'email',
  //     type: 'email',
  //     label: 'email',
  //     order: '1',
  //     fieldId: null,
  //     options: [],
  //     pattern: '/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$/',
  //     coreField: 1,
  //     dependsOn: null,
  //     maxLength: null,
  //     minLength: null,
  //     isEditable: true,
  //     isPIIField: null,
  //     isRequired: false,
  //     validation: ['string'],
  //     placeholder: 'ENTER_EMAIL',
  //     isMultiSelect: false,
  //     maxSelections: 0,
  //     sourceDetails: {},
  //   },
  //   {
  //     hint: null,
  //     name: 'mobile',
  //     type: 'numeric',
  //     label: 'phone_number',
  //     order: '1',
  //     fieldId: null,
  //     options: [],
  //     pattern: '/^[6-9]\\d{9}$/',
  //     coreField: 1,
  //     dependsOn: null,
  //     maxLength: 10,
  //     minLength: 10,
  //     isEditable: true,
  //     isPIIField: true,
  //     isRequired: true,
  //     validation: ['mobile'],
  //     placeholder: 'ENTER_PHONE_NUMBER',
  //     isMultiSelect: false,
  //     maxSelections: 0,
  //     sourceDetails: {},
  //   },
  //   {
  //     hint: null,
  //     name: 'dob',
  //     type: 'date',
  //     label: 'dob',
  //     order: '2',
  //     fieldId: null,
  //     options: [],
  //     pattern: null,
  //     coreField: 1,
  //     dependsOn: null,
  //     maxLength: null,
  //     minLength: null,
  //     isEditable: true,
  //     isPIIField: null,
  //     isRequired: true,
  //     validation: ['date'],
  //     placeholder: 'ENTER_DATE_OF_BIRTH',
  //     isMultiSelect: false,
  //     maxSelections: 0,
  //     sourceDetails: {},
  //   },
  //   {
  //     hint: null,
  //     name: 'gender',
  //     type: 'radio',
  //     label: 'WHATS_YOUR_GENDER',
  //     order: '2',
  //     fieldId: null,
  //     options: [
  //       {
  //         label: 'MALE',
  //         value: 'male',
  //       },
  //       {
  //         label: 'FEMALE',
  //         value: 'female',
  //       },
  //       {
  //         label: 'TRANSGENDER',
  //         value: 'transgender',
  //       },
  //     ],
  //     pattern: null,
  //     coreField: 1,
  //     dependsOn: null,
  //     maxLength: null,
  //     minLength: null,
  //     isEditable: true,
  //     isPIIField: null,
  //     isRequired: true,
  //     validation: ['string'],
  //     placeholder: '',
  //     isMultiSelect: false,
  //     maxSelections: 0,
  //     sourceDetails: {},
  //   },
  //   {
  //     order: '2',
  //     fieldId: '60f48fbf-d5e9-4a85-aa84-0739e727153c',
  //     coreField: 0,
  //     label: 'MOTHER_NAME',
  //     name: 'mother_name',
  //     type: 'text',
  //     isRequired: false,
  //     isEditable: true,
  //     isHidden: null,
  //     isPIIField: null,
  //     placeholder: '',
  //     validation: [],
  //     options: [],
  //     isMultiSelect: false,
  //     maxSelections: null,
  //     hint: null,
  //     pattern: '^(?=.*[a-zA-Z])[a-zA-Z ]+$',
  //     maxLength: null,
  //     minLength: '3',
  //     dependsOn: false,
  //     sourceDetails: null,
  //     ordering: 25,
  //     default: null,
  //   },
  //   {
  //     order: '3',
  //     fieldId: '9a4ad601-023b-467f-bbbe-bda1885f87c7',
  //     coreField: 0,
  //     label: 'HIGHEST_EDCATIONAL_QUALIFICATION_OR_LAST_PASSED_GRADE',
  //     name: 'class',
  //     type: 'drop_down',
  //     isRequired: true,
  //     isEditable: true,
  //     isHidden: null,
  //     isPIIField: null,
  //     placeholder: '',
  //     validation: [''],
  //     options: [
  //       {
  //         label: '1',
  //         value: '1',
  //       },
  //       {
  //         label: '2',
  //         value: '2',
  //       },
  //       {
  //         label: '3',
  //         value: '3',
  //       },
  //       {
  //         label: '4',
  //         value: '4',
  //       },
  //       {
  //         label: '5',
  //         value: '5',
  //       },
  //       {
  //         label: '6',
  //         value: '6',
  //       },
  //       {
  //         label: '7',
  //         value: '7',
  //       },
  //       {
  //         label: '8',
  //         value: '8',
  //       },
  //       {
  //         label: '9',
  //         value: '9',
  //       },
  //       {
  //         label: 'NO_SCHOOLING',
  //         value: 'no_schooling',
  //       },
  //     ],
  //     isMultiSelect: true,
  //     maxSelections: 1,
  //     hint: null,
  //     pattern: null,
  //     maxLength: null,
  //     minLength: null,
  //     dependsOn: false,
  //     sourceDetails: {
  //       source: 'fieldparams',
  //     },
  //     ordering: 9,
  //     default: null,
  //   },
  //   {
  //     order: '3',
  //     fieldId: 'ff472647-6c40-42e6-b200-dc74b241e915',
  //     coreField: 0,
  //     label: 'MARITAL_STATUS',
  //     name: 'marital_status',
  //     type: 'drop_down',
  //     isRequired: true,
  //     isEditable: true,
  //     isHidden: null,
  //     isPIIField: null,
  //     placeholder: '',
  //     validation: [],
  //     options: [
  //       {
  //         label: 'UNMARRIED',
  //         value: 'unmarried',
  //       },
  //       {
  //         label: 'MARRIED',
  //         value: 'married',
  //       },
  //       {
  //         label: 'DIVORCED',
  //         value: 'divorced',
  //       },
  //     ],
  //     isMultiSelect: true,
  //     maxSelections: 1,
  //     hint: null,
  //     pattern: null,
  //     maxLength: null,
  //     minLength: null,
  //     dependsOn: false,
  //     sourceDetails: {
  //       source: 'fieldparams',
  //     },
  //     ordering: 7,
  //     default: null,
  //   },

  //   {
  //     order: '3',
  //     fieldId: 'da594b2e-c645-4a96-af15-6e2d24587c9a',
  //     coreField: 0,
  //     label: 'TYPE_OF_PHONE_AVAILABLE',
  //     name: 'phone_type_available',
  //     type: 'radio',
  //     isRequired: true,
  //     isEditable: true,
  //     isHidden: null,
  //     isPIIField: null,
  //     placeholder: '',
  //     validation: [],
  //     options: [
  //       {
  //         label: 'SMARTPHONE',
  //         value: 'smartphone',
  //       },
  //       {
  //         label: 'KEYPAD',
  //         value: 'keypad',
  //       },
  //     ],
  //     isMultiSelect: false,
  //     maxSelections: null,
  //     hint: null,
  //     pattern: null,
  //     maxLength: null,
  //     minLength: null,
  //     dependsOn: false,
  //     sourceDetails: {
  //       source: 'fieldparams',
  //     },
  //     ordering: 11,
  //     default: null,
  //   },
  //   {
  //     order: '3',
  //     fieldId: 'd119d92f-fab7-4c7d-8370-8b40b5ed23dc',
  //     coreField: 0,
  //     label: 'DOES_THIS_PHONE_BELONG_TO_YOU',
  //     name: 'own_phone_check',
  //     type: 'radio',
  //     isRequired: true,
  //     isEditable: true,
  //     isHidden: null,
  //     isPIIField: null,
  //     placeholder: '',
  //     validation: [],
  //     options: [
  //       {
  //         label: 'YES',
  //         value: 'yes',
  //       },
  //       {
  //         label: 'NO',
  //         value: 'no',
  //       },
  //     ],
  //     isMultiSelect: false,
  //     maxSelections: null,
  //     hint: null,
  //     pattern: null,
  //     maxLength: null,
  //     minLength: null,
  //     dependsOn: false,
  //     sourceDetails: {
  //       source: 'fieldparams',
  //     },
  //     ordering: 12,
  //     default: null,
  //   },
  //   {
  //     api: {
  //       url: 'https://dev-interface.prathamdigital.org/interface/v1/fields/options/read',
  //       method: 'POST',
  //       options: {
  //         label: 'label',
  //         value: 'value',
  //         optionObj: 'result.values',
  //       },
  //       payload: {
  //         sort: ['state_name', 'asc'],
  //         fieldName: 'state',
  //       },
  //       callType: 'initial',
  //     },
  //     order: '4',
  //     fieldId: '6469c3ac-8c46-49d7-852a-00f9589737c5',
  //     coreField: 0,
  //     label: 'STATE',
  //     name: 'state',
  //     type: 'drop_down',
  //     isRequired: false,
  //     isEditable: true,
  //     isHidden: null,
  //     isPIIField: null,
  //     placeholder: '',
  //     validation: [],
  //     options: [
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //       {},
  //     ],
  //     isMultiSelect: true,
  //     maxSelections: 1,
  //     hint: null,
  //     pattern: null,
  //     maxLength: null,
  //     minLength: null,
  //     dependsOn: false,
  //     sourceDetails: {
  //       table: 'state',
  //       source: 'table',
  //     },
  //     ordering: 17,
  //     default: null,
  //   },
  //   {
  //     api: {
  //       url: 'https://dev-interface.prathamdigital.org/interface/v1/fields/options/read',
  //       method: 'POST',
  //       options: {
  //         label: 'label',
  //         value: 'value',
  //         optionObj: 'result.values',
  //       },
  //       payload: {
  //         sort: ['district_name', 'asc'],
  //         fieldName: 'district',
  //         controllingfieldfk: '**',
  //       },
  //       callType: 'dependent',
  //       dependent: 'state',
  //     },
  //     order: '4',
  //     fieldId: 'b61edfc6-3787-4079-86d3-37262bf23a9e',
  //     coreField: 0,
  //     label: 'DISTRICT',
  //     name: 'district',
  //     type: 'drop_down',
  //     isRequired: false,
  //     isEditable: true,
  //     isHidden: null,
  //     isPIIField: null,
  //     placeholder: '',
  //     validation: [],
  //     options: [],
  //     isMultiSelect: true,
  //     maxSelections: 1,
  //     hint: null,
  //     pattern: null,
  //     maxLength: null,
  //     minLength: null,
  //     dependsOn: 'state',
  //     sourceDetails: {
  //       table: 'district',
  //       source: 'table',
  //     },
  //     ordering: 19,
  //     default: null,
  //   },
  //   {
  //     api: {
  //       url: 'https://dev-interface.prathamdigital.org/interface/v1/fields/options/read',
  //       method: 'POST',
  //       options: {
  //         label: 'label',
  //         value: 'value',
  //         optionObj: 'result.values',
  //       },
  //       payload: {
  //         sort: ['block_name', 'asc'],
  //         fieldName: 'block',
  //         controllingfieldfk: '**',
  //       },
  //       callType: 'dependent',
  //       dependent: 'district',
  //     },
  //     order: '4',
  //     fieldId: '4aab68ae-8382-43aa-a45a-e9b239319857',
  //     coreField: 0,
  //     label: 'BLOCK',
  //     name: 'block',
  //     type: 'drop_down',
  //     isRequired: false,
  //     isEditable: true,
  //     isHidden: null,
  //     isPIIField: null,
  //     placeholder: '',
  //     validation: [],
  //     options: [],
  //     isMultiSelect: true,
  //     maxSelections: 1,
  //     hint: null,
  //     pattern: null,
  //     maxLength: null,
  //     minLength: null,
  //     dependsOn: 'district',
  //     sourceDetails: {
  //       table: 'block',
  //       source: 'table',
  //     },
  //     ordering: 16,
  //     default: null,
  //   },
  //   {
  //     api: {
  //       url: 'https://dev-interface.prathamdigital.org/interface/v1/fields/options/read',
  //       method: 'POST',
  //       options: {
  //         label: 'label',
  //         value: 'value',
  //         optionObj: 'result.values',
  //       },
  //       payload: {
  //         sort: ['village_name', 'asc'],
  //         fieldName: 'village',
  //         controllingfieldfk: '**',
  //       },
  //       callType: 'dependent',
  //       dependent: 'block',
  //     },
  //     order: '4',
  //     fieldId: '8e9bb321-ff99-4e2e-9269-61e863dd0c54',
  //     coreField: 0,
  //     label: 'VILLAGE',
  //     name: 'village',
  //     type: 'drop_down',
  //     isRequired: false,
  //     isEditable: true,
  //     isHidden: null,
  //     isPIIField: null,
  //     placeholder: '',
  //     validation: [],
  //     options: [],
  //     isMultiSelect: true,
  //     maxSelections: 100,
  //     hint: null,
  //     pattern: null,
  //     maxLength: null,
  //     minLength: null,
  //     dependsOn: 'block',
  //     sourceDetails: {
  //       table: 'village',
  //       source: 'table',
  //     },
  //     ordering: 26,
  //     default: null,
  //   },
  //   // {
  //   //   order: '4',
  //   //   fieldId: '3d23ef47-30b3-4fe4-833c-42f71be27e6b',
  //   //   coreField: 0,
  //   //   label: 'PREFERRED_LANGUAGE_OF_LEARNING',
  //   //   name: 'preferred language',
  //   //   type: 'text',
  //   //   isRequired: false,
  //   //   isEditable: true,
  //   //   isHidden: null,
  //   //   isPIIField: null,
  //   //   placeholder: '',
  //   //   validation: ['required'],
  //   //   options: [
  //   //     {
  //   //       label: 'ENGLISH',
  //   //       value: 'english',
  //   //     },
  //   //     {
  //   //       label: 'HINDI',
  //   //       value: 'hindi',
  //   //     },
  //   //     {
  //   //       label: 'MARATHI',
  //   //       value: 'marathi',
  //   //     },
  //   //     {
  //   //       label: 'BENGALI',
  //   //       value: 'bengali',
  //   //     },
  //   //     {
  //   //       label: 'TELUGU',
  //   //       value: 'telugu',
  //   //     },
  //   //     {
  //   //       label: 'KANNADA',
  //   //       value: 'kannada',
  //   //     },
  //   //     {
  //   //       label: 'GUJARATI',
  //   //       value: 'gujarati',
  //   //     },
  //   //     {
  //   //       label: 'URDU',
  //   //       value: 'urdu',
  //   //     },
  //   //   ],
  //   //   isMultiSelect: false,
  //   //   maxSelections: null,
  //   //   hint: null,
  //   //   pattern: null,
  //   //   maxLength: null,
  //   //   minLength: null,
  //   //   dependsOn: false,
  //   //   sourceDetails: {
  //   //     source: 'fieldparams',
  //   //   },
  //   //   ordering: 25,
  //   //   default: null,
  //   // },
  //   {
  //     hint: null,
  //     name: 'username',
  //     type: 'text',
  //     label: 'USERNAME',
  //     order: '5',
  //     fieldId: null,
  //     options: [],
  //     pattern: '^[a-zA-Z0-9.@]+$',
  //     coreField: 1,
  //     dependsOn: null,
  //     maxLength: null,
  //     minLength: 3,
  //     isEditable: true,
  //     isPIIField: null,
  //     isRequired: true,
  //     validation: ['string'],
  //     placeholder: 'USERNAME',
  //     isMultiSelect: false,
  //     maxSelections: 0,
  //     sourceDetails: {},
  //   },
  //   {
  //     hint: null,
  //     name: 'password',
  //     type: 'password',
  //     label: 'password',
  //     order: '5',
  //     fieldId: null,
  //     options: [],
  //     pattern: null,
  //     coreField: 1,
  //     dependsOn: null,
  //     maxLength: null,
  //     minLength: 4,
  //     isEditable: true,
  //     isPIIField: null,
  //     isRequired: true,
  //     validation: ['string'],
  //     placeholder: 'password',
  //     isMultiSelect: false,
  //     maxSelections: 0,
  //     sourceDetails: {},
  //   },
  //   {
  //     hint: null,
  //     name: 'confirm_password',
  //     type: 'confirm_password',
  //     label: 'confirm_password',
  //     order: '5',
  //     fieldId: null,
  //     options: [],
  //     pattern: null,
  //     coreField: 1,
  //     dependsOn: null,
  //     maxLength: null,
  //     minLength: 4,
  //     isEditable: true,
  //     isPIIField: null,
  //     isRequired: true,
  //     validation: ['string'],
  //     placeholder: 'confirm_password',
  //     isMultiSelect: false,
  //     maxSelections: 0,
  //     sourceDetails: {},
  //   },
  //   {
  //     order: '5',
  //     fieldId: 'd7a56014-0b9a-4f16-b07e-88baea79576d',
  //     coreField: 0,
  //     label: 'NAME_OF_GUARDIAN',
  //     name: 'guardian_name',
  //     type: 'text',
  //     isRequired: false,
  //     isEditable: true,
  //     isHidden: null,
  //     isPIIField: null,
  //     placeholder: '',
  //     validation: [],
  //     options: [],
  //     isMultiSelect: false,
  //     maxSelections: null,
  //     hint: null,
  //     pattern: '^(?=.*[a-zA-Z])[a-zA-Z ]+$',
  //     maxLength: null,
  //     minLength: '3',
  //     dependsOn: 'dob',
  //     sourceDetails: null,
  //     ordering: 25,
  //     default: null,
  //   },
  //   {
  //     order: '5',
  //     fieldId: '3a7bf305-6bac-4377-bf09-f38af866105c',
  //     coreField: 0,
  //     label: 'RELATION_WITH_GUARDIAN',
  //     name: 'guardian_relation',
  //     type: 'text',
  //     isRequired: false,
  //     isEditable: true,
  //     isHidden: null,
  //     isPIIField: null,
  //     placeholder: '',
  //     validation: [],
  //     options: [],
  //     isMultiSelect: false,
  //     maxSelections: null,
  //     hint: null,
  //     pattern: null,
  //     maxLength: null,
  //     minLength: null,
  //     dependsOn: 'dob',
  //     sourceDetails: null,
  //     ordering: 25,
  //     default: null,
  //   },
  //   {
  //     order: '5',
  //     fieldId: '7ecaa845-901a-4ac7-a136-eed087f3b85b',
  //     coreField: 0,
  //     label: 'PARENT_GUARDIAN_PHONE_NO',
  //     name: 'parent_phone',
  //     type: 'numeric',
  //     isRequired: true,
  //     isEditable: true,
  //     isHidden: null,
  //     isPIIField: null,
  //     placeholder: '',
  //     validation: ['numeric'],
  //     options: [],
  //     isMultiSelect: false,
  //     maxSelections: null,
  //     hint: null,
  //     pattern: null,
  //     maxLength: null,
  //     minLength: null,
  //     dependsOn: false,
  //     sourceDetails: null,
  //     ordering: 25,
  //     default: null,
  //   },
  //   {
  //     api: {
  //       url: '/api/dynamic-form/get-tenant',
  //       method: 'GET',
  //       options: {
  //         label: 'label',
  //         value: 'value',
  //         optionObj: 'options',
  //       },
  //       payload: {
  //         code: 'board',
  //         fetchUrl:
  //           'https://dev-interface.prathamdigital.org//interface/v1/tenant/read',
  //       },
  //       callType: 'initial',
  //     },
  //     hint: null,
  //     name: 'program',
  //     type: 'cradio',
  //     label: 'program',
  //     order: '6',
  //     fieldId: null,
  //     options: [],
  //     pattern: null,
  //     coreField: 1,
  //     dependsOn: null,
  //     maxLength: null,
  //     minLength: 4,
  //     isEditable: true,
  //     isPIIField: null,
  //     isRequired: true,
  //     validation: ['string'],
  //     placeholder: 'program',
  //     isMultiSelect: false,
  //     maxSelections: 0,
  //     sourceDetails: {},
  //   },
  // ];

  const fetchData = async () => {
    const data = await getStudentForm();
    if (data?.error) {
      setNetworkError(true);
    } else {
      await fetchstates();
      setDataInStorage('studentForm', JSON.stringify(data?.fields));
      let schema = data?.fields;
      setMainSchema(schema);
      getLocation(); // GetLocation Comment
      setNetworkError(false);
    }

    setLoading(false);
  };

  useEffect(() => {
    fetchData();
  }, []);

  return loading ? (
    <Loading />
  ) : (
    <SafeAreaView style={styles.container}>
      <RegistrationForm geoData={geoData} fields={mainSchema} />
      <NetworkAlert onTryAgain={fetchData} isConnected={!networkError} />
    </SafeAreaView>
  );
};
const styles = StyleSheet.create({
  container: {
    backgroundColor: 'white',
    flex: 1,
  },

  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
  },
});
export default RegisterScreen;
